### ISSUE TITLE
✨ 서울청 공문 추가

### ISSUE THREAD

**Issue by ChooSeoyeon** [FISOLUTION/BE_POLICE_LEGACY_PUBLIC#43]
## 📌 Feature Issue
- 서울청 공문을 추가해 메일을 전송한다.

## 📝 To-do
- [ ] 서버에 서울청 메일 추가
- [ ] 서울청 처리 로직 추가
- [ ] 메일 전송 테스트
