### ISSUE TITLE
✨ 경상남도 경찰청 공문 추가

### ISSUE THREAD

**Issue by ChooSeoyeon** [FISOLUTION/BE_POLICE_LEGACY_PUBLIC#52]
## 📌 Feature Issue
- 경상남도 경찰청 공문을 추가해 메일을 전송한다.

## 📝 To-do
- [x] 서버에 경상남도 경찰청 공문 추가
- [x] 경상남도 처리 로직 추가
- [x] 메일 전송 테스트
- [x] prod 서버에 5시 이후 배포

**Comment by ChooSeoyeon** [comment]
일반적인 오류(서버 오류 설명 제공).
오류 코드: 4
서버 오류 메시지:: Failure

오류 코드 4의 일반적인 이유는 다음과 같습니다:

이미 존재하는 파일로 파일 이름을 변경
이미 존재하는 디렉터리 생성
다른 파일 시스템(HDD)로 원격 파일 이동
전체 파일시스템(HDD)로 파일 업로드
사용자 디스크 할당량 초과
