### ISSUE TITLE
✨ Basetime Entity 적용

### ISSUE THREAD

**Issue by ChooSeoyeon** [FISOLUTION/BE_POLICE_LEGACY_PUBLIC#90]
## 📌 Feature Issue
- 모든 테이블의 생성과 업데이트 시간을 추적할 수 있다.

## 📝 To-do
- [x] createdAt, updatedAt 가지는 Basetime Entity 생성
- [x] 모든 entity에 basetime Entity 적용
- [x] db에 모든 테이블에 createdAt과 updatedAt 추가
